all:
  children:
    control:
      hosts:
        192.168.0.153:
        192.168.0.154:
      vars:
        ansible_network_os: eos
        ansible_connection: network_cli
        ansible_user: admin
        ansible_password: password123
